/***
Revisión de FGU
***/

SELECT * FROM "CDM_LMS"."COURSE_ITEM"
WHERE NAME LIKE '%T1-S03-A01'
AND  COURSE_ID = '271556'
AND  COURSE_TOOL_ID = '37474256'
AND  ITEM_TYPE = 'TEST'

SELECT * FROM CDM_LMS.COURSE_TOOL
WHERE   ID = '37474256'
AND     COURSE_ID = '271556'
AND     TOOD_ID = '226'
AND     COURSE_SOURCE_ID = '53339'


SELECT distinct item_type FROM "CDM_LMS"."COURSE_ITEM"


list items

BLACKBOARD_COLLABORATE
TEST_QUESTION
TEST


SELECT * FROM "CDM_LMS"."COURSE"
WHERE  ID = 271531
/*
SELECT  COUR.ID,
        COUR.TERM_ID,
        COUR.SOURCE_ID,
        COUR.NAME,
        COUR.COURSE_NUMBER,
        COUR.ENABLED_IND,
        COUR.ROW_INSERTED_TIME,
        COUR.ROW_DELETED_TIME,
        COUR.MODIFIED_TIME,
        COUR.CREATED_TIME,
        COUR_IT.ID,
        COUR_IT.COURSE_TOOL_ID,
        COUR_IT.NAME,
        COUR_IT.SOURCE_ID*/
        
        SELECT *
FROM    "CDM_LMS"."COURSE" COUR
LEFT JOIN "CDM_LMS"."COURSE_ITEM" COUR_IT ON
        COUR_IT.COURSE_ID = COUR.ID
WHERE   COURSE_NUMBER LIKE '202036_%'
and     COUR_IT.NAME = 'PRUEBA T1-S03-A01'
AND     item_type IN ('TEST','TEST_QUESTION')


DISTINCT PER.ID,
        PER.SOURCE_ID,
        PER.FIRST_NAME,
        PER.LAST_NAME,
        PER.EMAIL,
        PER.STAGE:batch_uid,
        PER.INSTITUTION_ROLE_SOURCE_DESC,
        PERCOU.ID PER_COUR_ID,
        PERCOU.COURSE_ID    COUR_ID,
        COU.ID,
        COU.NAME,
        COU.COURSE_NUMBER,
        GRAD.SCORE,
        GRAD.POSSIBLE_SCORE

SELECT * 
FROM        CDM_LMS.PERSON PER
LEFT JOIN   cdm_lms.PERSON_COURSE PERCOU ON
            PER.ID = PERCOU.PERSON_ID
LEFT JOIN   cdm_lms.course COU ON
            COU.ID = PERCOU.COURSE_ID
LEFT JOIN   cdm_lms.grade GRAD ON
            GRAD.PERSON_COURSE_ID = PERCOU.ID 
WHERE       COURSE_NUMBER LIKE '202036_%'
AND         COU.NAME LIKE '%PRFG 001 - Formacion General Universitaria - Oto20'  
--AND         COUR_ITEM.NAME LIKE '%T1-S03-A01'
AND         PER.ID = 1826560


SELECT * FROM "CDM_LMS"."COURSE_ITEM"
WHERE NAME LIKE '%T1-S03-A01'
